###############################################################################
# Created by write_sdc
# Tue Sep 20 18:57:42 2022
###############################################################################
current_design IMemory
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 1000.0000 [get_ports {clk}]
set_clock_transition 0.1500 [get_clocks {clk}]
set_clock_uncertainty 0.2500 clk
set_propagated_clock [get_clocks {clk}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_input[0]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_input[10]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_input[11]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_input[12]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_input[13]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_input[14]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_input[15]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_input[16]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_input[17]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_input[18]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_input[19]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_input[1]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_input[20]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_input[21]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_input[22]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_input[23]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_input[24]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_input[25]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_input[26]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_input[27]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_input[28]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_input[29]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_input[2]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_input[30]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_input[31]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_input[3]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_input[4]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_input[5]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_input[6]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_input[7]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_input[8]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_input[9]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_select[0]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_select[1]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_select[2]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_select[3]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_write}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[0]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[10]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[11]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[12]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[13]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[14]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[15]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[16]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[17]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[18]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[19]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[1]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[20]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[21]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[22]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[23]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[24]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[25]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[26]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[27]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[28]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[29]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[2]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[30]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[31]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[3]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[4]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[5]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[6]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[7]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[8]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pc[9]}]
set_input_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rst_n}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {funct3[0]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {funct3[1]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {funct3[2]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {funct7[0]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {funct7[1]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {funct7[2]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {funct7[3]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {funct7[4]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {funct7[5]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {funct7[6]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {immediate[0]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {immediate[10]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {immediate[11]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {immediate[12]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {immediate[13]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {immediate[14]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {immediate[15]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {immediate[16]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {immediate[17]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {immediate[18]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {immediate[19]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {immediate[1]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {immediate[20]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {immediate[21]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {immediate[22]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {immediate[23]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {immediate[24]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {immediate[25]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {immediate[26]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {immediate[27]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {immediate[28]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {immediate[29]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {immediate[2]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {immediate[30]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {immediate[31]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {immediate[3]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {immediate[4]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {immediate[5]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {immediate[6]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {immediate[7]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {immediate[8]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {immediate[9]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction_type_output[0]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction_type_output[1]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction_type_output[2]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction_type_output[3]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction_type_output[4]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {instruction_type_output[5]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_read[0]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_read[10]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_read[11]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_read[12]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_read[13]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_read[14]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_read[15]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_read[16]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_read[17]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_read[18]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_read[19]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_read[1]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_read[20]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_read[21]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_read[22]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_read[23]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_read[24]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_read[25]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_read[26]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_read[27]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_read[28]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_read[29]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_read[2]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_read[30]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_read[31]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_read[3]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_read[4]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_read[5]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_read[6]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_read[7]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_read[8]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {la_instruction_read[9]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {opcode[0]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {opcode[1]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {opcode[2]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {opcode[3]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {opcode[4]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {opcode[5]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {opcode[6]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rd[0]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rd[1]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rd[2]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rd[3]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rd[4]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rs1[0]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rs1[1]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rs1[2]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rs1[3]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rs1[4]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rs2[0]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rs2[1]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rs2[2]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rs2[3]}]
set_output_delay 200.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rs2[4]}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {funct3[2]}]
set_load -pin_load 0.0334 [get_ports {funct3[1]}]
set_load -pin_load 0.0334 [get_ports {funct3[0]}]
set_load -pin_load 0.0334 [get_ports {funct7[6]}]
set_load -pin_load 0.0334 [get_ports {funct7[5]}]
set_load -pin_load 0.0334 [get_ports {funct7[4]}]
set_load -pin_load 0.0334 [get_ports {funct7[3]}]
set_load -pin_load 0.0334 [get_ports {funct7[2]}]
set_load -pin_load 0.0334 [get_ports {funct7[1]}]
set_load -pin_load 0.0334 [get_ports {funct7[0]}]
set_load -pin_load 0.0334 [get_ports {immediate[31]}]
set_load -pin_load 0.0334 [get_ports {immediate[30]}]
set_load -pin_load 0.0334 [get_ports {immediate[29]}]
set_load -pin_load 0.0334 [get_ports {immediate[28]}]
set_load -pin_load 0.0334 [get_ports {immediate[27]}]
set_load -pin_load 0.0334 [get_ports {immediate[26]}]
set_load -pin_load 0.0334 [get_ports {immediate[25]}]
set_load -pin_load 0.0334 [get_ports {immediate[24]}]
set_load -pin_load 0.0334 [get_ports {immediate[23]}]
set_load -pin_load 0.0334 [get_ports {immediate[22]}]
set_load -pin_load 0.0334 [get_ports {immediate[21]}]
set_load -pin_load 0.0334 [get_ports {immediate[20]}]
set_load -pin_load 0.0334 [get_ports {immediate[19]}]
set_load -pin_load 0.0334 [get_ports {immediate[18]}]
set_load -pin_load 0.0334 [get_ports {immediate[17]}]
set_load -pin_load 0.0334 [get_ports {immediate[16]}]
set_load -pin_load 0.0334 [get_ports {immediate[15]}]
set_load -pin_load 0.0334 [get_ports {immediate[14]}]
set_load -pin_load 0.0334 [get_ports {immediate[13]}]
set_load -pin_load 0.0334 [get_ports {immediate[12]}]
set_load -pin_load 0.0334 [get_ports {immediate[11]}]
set_load -pin_load 0.0334 [get_ports {immediate[10]}]
set_load -pin_load 0.0334 [get_ports {immediate[9]}]
set_load -pin_load 0.0334 [get_ports {immediate[8]}]
set_load -pin_load 0.0334 [get_ports {immediate[7]}]
set_load -pin_load 0.0334 [get_ports {immediate[6]}]
set_load -pin_load 0.0334 [get_ports {immediate[5]}]
set_load -pin_load 0.0334 [get_ports {immediate[4]}]
set_load -pin_load 0.0334 [get_ports {immediate[3]}]
set_load -pin_load 0.0334 [get_ports {immediate[2]}]
set_load -pin_load 0.0334 [get_ports {immediate[1]}]
set_load -pin_load 0.0334 [get_ports {immediate[0]}]
set_load -pin_load 0.0334 [get_ports {instruction_type_output[5]}]
set_load -pin_load 0.0334 [get_ports {instruction_type_output[4]}]
set_load -pin_load 0.0334 [get_ports {instruction_type_output[3]}]
set_load -pin_load 0.0334 [get_ports {instruction_type_output[2]}]
set_load -pin_load 0.0334 [get_ports {instruction_type_output[1]}]
set_load -pin_load 0.0334 [get_ports {instruction_type_output[0]}]
set_load -pin_load 0.0334 [get_ports {la_instruction_read[31]}]
set_load -pin_load 0.0334 [get_ports {la_instruction_read[30]}]
set_load -pin_load 0.0334 [get_ports {la_instruction_read[29]}]
set_load -pin_load 0.0334 [get_ports {la_instruction_read[28]}]
set_load -pin_load 0.0334 [get_ports {la_instruction_read[27]}]
set_load -pin_load 0.0334 [get_ports {la_instruction_read[26]}]
set_load -pin_load 0.0334 [get_ports {la_instruction_read[25]}]
set_load -pin_load 0.0334 [get_ports {la_instruction_read[24]}]
set_load -pin_load 0.0334 [get_ports {la_instruction_read[23]}]
set_load -pin_load 0.0334 [get_ports {la_instruction_read[22]}]
set_load -pin_load 0.0334 [get_ports {la_instruction_read[21]}]
set_load -pin_load 0.0334 [get_ports {la_instruction_read[20]}]
set_load -pin_load 0.0334 [get_ports {la_instruction_read[19]}]
set_load -pin_load 0.0334 [get_ports {la_instruction_read[18]}]
set_load -pin_load 0.0334 [get_ports {la_instruction_read[17]}]
set_load -pin_load 0.0334 [get_ports {la_instruction_read[16]}]
set_load -pin_load 0.0334 [get_ports {la_instruction_read[15]}]
set_load -pin_load 0.0334 [get_ports {la_instruction_read[14]}]
set_load -pin_load 0.0334 [get_ports {la_instruction_read[13]}]
set_load -pin_load 0.0334 [get_ports {la_instruction_read[12]}]
set_load -pin_load 0.0334 [get_ports {la_instruction_read[11]}]
set_load -pin_load 0.0334 [get_ports {la_instruction_read[10]}]
set_load -pin_load 0.0334 [get_ports {la_instruction_read[9]}]
set_load -pin_load 0.0334 [get_ports {la_instruction_read[8]}]
set_load -pin_load 0.0334 [get_ports {la_instruction_read[7]}]
set_load -pin_load 0.0334 [get_ports {la_instruction_read[6]}]
set_load -pin_load 0.0334 [get_ports {la_instruction_read[5]}]
set_load -pin_load 0.0334 [get_ports {la_instruction_read[4]}]
set_load -pin_load 0.0334 [get_ports {la_instruction_read[3]}]
set_load -pin_load 0.0334 [get_ports {la_instruction_read[2]}]
set_load -pin_load 0.0334 [get_ports {la_instruction_read[1]}]
set_load -pin_load 0.0334 [get_ports {la_instruction_read[0]}]
set_load -pin_load 0.0334 [get_ports {opcode[6]}]
set_load -pin_load 0.0334 [get_ports {opcode[5]}]
set_load -pin_load 0.0334 [get_ports {opcode[4]}]
set_load -pin_load 0.0334 [get_ports {opcode[3]}]
set_load -pin_load 0.0334 [get_ports {opcode[2]}]
set_load -pin_load 0.0334 [get_ports {opcode[1]}]
set_load -pin_load 0.0334 [get_ports {opcode[0]}]
set_load -pin_load 0.0334 [get_ports {rd[4]}]
set_load -pin_load 0.0334 [get_ports {rd[3]}]
set_load -pin_load 0.0334 [get_ports {rd[2]}]
set_load -pin_load 0.0334 [get_ports {rd[1]}]
set_load -pin_load 0.0334 [get_ports {rd[0]}]
set_load -pin_load 0.0334 [get_ports {rs1[4]}]
set_load -pin_load 0.0334 [get_ports {rs1[3]}]
set_load -pin_load 0.0334 [get_ports {rs1[2]}]
set_load -pin_load 0.0334 [get_ports {rs1[1]}]
set_load -pin_load 0.0334 [get_ports {rs1[0]}]
set_load -pin_load 0.0334 [get_ports {rs2[4]}]
set_load -pin_load 0.0334 [get_ports {rs2[3]}]
set_load -pin_load 0.0334 [get_ports {rs2[2]}]
set_load -pin_load 0.0334 [get_ports {rs2[1]}]
set_load -pin_load 0.0334 [get_ports {rs2[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {clk}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_write}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {rst_n}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_input[31]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_input[30]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_input[29]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_input[28]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_input[27]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_input[26]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_input[25]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_input[24]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_input[23]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_input[22]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_input[21]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_input[20]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_input[19]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_input[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_input[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_input[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_input[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_input[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_input[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_input[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_input[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_input[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_input[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_input[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_input[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_input[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_input[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_input[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_input[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_input[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_input[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_input[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_select[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_select[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_select[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_instruction_select[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pc[31]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pc[30]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pc[29]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pc[28]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pc[27]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pc[26]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pc[25]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pc[24]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pc[23]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pc[22]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pc[21]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pc[20]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pc[19]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pc[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pc[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pc[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pc[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pc[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pc[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pc[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pc[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pc[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pc[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pc[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pc[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pc[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pc[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pc[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pc[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pc[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pc[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pc[0]}]
set_timing_derate -early 0.9500
set_timing_derate -late 1.0500
###############################################################################
# Design Rules
###############################################################################
set_max_fanout 10.0000 [current_design]
